### ISSUE TITLE
misp-modules not working after upgrading to 2.5

### ISSUE THREAD

**Issue by arnauos** [amuehlem/MISP-RPM#105]
Hi, after upgrading to release 2.5 on RHEL8, the misp-modules service stopped working (the service does not start).

I'm not sure what the problem exactly is or how I could diagnose it, any ideas?

```
service misp-modules status
Redirecting to /bin/systemctl status misp-modules.service
● misp-modules.service - MISP enhancement modules
   Loaded: loaded (/etc/systemd/system/misp-modules.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2024-12-18 12:53:39 CET; 47s ago
  Process: 3765031 ExecStart=/var/www/cgi-bin/misp-modules-venv/bin/misp-modules -l 127.0.0.1 -s (code=exited, status=1/FAILURE)
 Main PID: 3765031 (code=exited, status=1/FAILURE)
```

```
Installed Packages
misp.x86_64                                                                      2.5.3-1.el8
misp-modules.x86_64                                                              2.4.199-1.el8
misp-python-virtualenv.x86_64                                                    2.5.3-1.el8
misp-release.noarch                                                              1.1-2.el8
```

**Comment by amuehlem** [comment]
Can you check /var/log/messages for errors? ```grep misp-modules /var/log/messages``` should reveal what goes wrong.

**Comment by arnauos** [comment]
Hi, I see this:

```
Dec 18 14:42:47 misp-srv systemd[1]: misp-modules.service: Service RestartSec=1min expired, scheduling restart.
Dec 18 14:42:47 misp-srv systemd[1]: misp-modules.service: Scheduled restart job, restart counter is at
22695.
Dec 18 14:42:47 misp-srv systemd[1]: Stopped MISP enhancement modules.
Dec 18 14:42:47 misp-srv systemd[1]: Started MISP enhancement modules.
Dec 18 14:42:49 misp-srv misp-modules[3801016]: /var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/clamd/_init_.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  _version_ = _import_('pkg_resources').get_distribution('clamd').version
Dec 18 14:42:49 misp-srv misp-modules[3801016]: /var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/pkg_resources/_init_.py:3154: DeprecationWarning: Deprecated call to ⁠ pkg_resources.declare_namespace('mpl_toolkits') ⁠.
Dec 18 14:42:49 misp-srv misp-modules[3801016]: Implementing implicit namespace packages (as specified in PEP 420) is preferred to ⁠ pkg_resources.declare_namespace ⁠. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  declare_namespace(pkg)
Dec 18 14:42:49 misp-srv misp-modules[3801016]: ERROR:root:'type' object is not subscriptable
Dec 18 14:42:49 misp-srv misp-modules[3801016]: Traceback (most recent call last):
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  File "/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/misp_modules/_init_.py", line 94, in <module>
Dec 18 14:42:49 misp-srv misp-modules[3801016]:    from .modules import *  # noqa
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  File "/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/misp_modules/modules/_init_.py", line 1, in <module>
Dec 18 14:42:49 misp-srv misp-modules[3801016]:    from .expansion import *  # noqa
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  File "/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/misp_modules/modules/expansion/vmware_nsx.py", line 23, in <module>
Dec 18 14:42:49 misp-srv misp-modules[3801016]:    from tau_clients import nsx_defender
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  File "/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/tau_clients/nsx_defender/_init_.py", line 40, in <module>
Dec 18 14:42:49 misp-srv misp-modules[3801016]:    class AbstractClient(abc.ABC):
Dec 18 14:42:49 misp-srv misp-modules[3801016]:  File "/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/tau_clients/nsx_defender/_init_.py", line 169, in AbstractClient
Dec 18 14:42:49 misp-srv misp-modules[3801016]:    def parse_header(cls, content_disposition: str) -> tuple[str, dict]:
Dec 18 14:42:49 misp-srv misp-modules[3801016]: TypeError: 'type' object is not subscriptable
Dec 18 14:42:49 misp-srv misp-modules[3801016]: 2024-12-18 14:42:49,653 - misp-modules - INFO - Launch MISP modules server from package.
Dec 18 14:42:49 misp-srv misp-modules[3801016]: 2024-12-18 14:42:49,655 - misp-modules - INFO - Helper loaded cache
Dec 18 14:42:49 misp-srv misp-modules[3801016]: 2024-12-18 14:42:49,655 - misp-modules - ERROR - Unableto load MISP modules from package.
Dec 18 14:42:50 misp-srv systemd[1]: misp-modules.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 14:42:50 misp-srv systemd[1]: misp-modules.service: Failed with result 'exit-code
```

**Comment by isotonicuk** [comment]
Out of interest, how would I get access to the 2.5 rpm for misp-modules. I can only seem to pull the 2.4 version.

**Comment by amuehlem** [comment]
There is no 2.5 Version for the misp modules, the latest is 2.4.199
https://github.com/misp/misp-modules

I'll check your error messages and have to compare to my test system.

**Comment by amuehlem** [comment]
looks like there is a problem with the vmware_nsx submodule. As a workaround you can remove this submodule 'vmware_nsx' in the file
/var/www/cgi-bin/misp-modules-venv/lib64/python3.8/site-packages/misp_modules/modules/expansion/__init__.py.
Without this submodule the misp-modules should start without any issues.

**Comment by arnauos** [comment]
Thanks! That did work and the modules service is up again 👍

**Comment by amuehlem** [comment]
I've found the problem, some modules require python3.9. I'm building a new version for RHEL8 and will test if the vmware_nsx module will work with python3.9.

**Comment by amuehlem** [comment]
I've created a new RPM misp-modules-2.4.199-2 and pushed it on the repository. This will use a python virtual environment running python 3.9 for the modules and the vmware_nsx will work as expected and does not need to be removed. If you upgrade to this version, the modules should start without any changes to any of the files.

**Comment by arnauos** [comment]
Updated and it seems to be working without issue. Thanks!
