### ISSUE TITLE
Missing dependency in python36-stix2 rpm?

### ISSUE THREAD

**Issue by racco42** [amuehlem/MISP-RPM#53]
Hi,

I was trying to do clean install of MISP from RPMs (great job BTW making those BTW) and fell into following trap:
When trying to import STIX file, I got the following error:

Traceback (most recent call last):
  File "/app/MISP/app/files/scripts/stix2/stix2misp.py", line 24, in <module>
    import stix2
  File "/usr/lib/python3.6/site-packages/stix2/__init__.py", line 28, in <module>
    from .datastore import CompositeDataSource
  File "/usr/lib/python3.6/site-packages/stix2/datastore/__init__.py", line 20, in <module>
    from stix2.datastore.filters import Filter, FilterSet
  File "/usr/lib/python3.6/site-packages/stix2/datastore/filters.py", line 8, in <module>
    import stix2.utils
  File "/usr/lib/python3.6/site-packages/stix2/utils.py", line 9, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

It can be easily fixed by running "yum install python36-pytz", but seems to be missing dependency for the RPM/library.

Thanks!

**Comment by amuehlem** [comment]
Thank you for pointing this out, I've added python36-pytz as a dependency to this package.
